### ISSUE TITLE
Not working with Reveal.js 3.7.0

### ISSUE THREAD

**Issue by bcouetil** [denniskniep/reveal.js-plugin-spotlight#3]
Hey,

Thank you for this great idea and sharing !

I can't make it work with Reveal.js 3.7.0. I've put some console logs, so I know it operates in my presentation, but I encounter different problems on different browsers : 
- on Firefox, the spotlight appears on click but does not move with the mouse
- on Chrome, the spotlight does not appear at all

Here is a sample presentation ('p' for presentation mode) : https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html

**Comment by bcouetil** [comment]
I've played a bit with the options, and here is the status : 
- left-click in presentation mode : no movement
- right-click in presentation mode : OK, movement (but not ideal since a menu is shown at the end)
- alternative key ('L' in above presentation) : OK, and no need for presentation mode

I guess that for now, I'll stick with the alternative key !

**Comment by denniskniep** [comment]
Hello,
sorry for the late reply.

For me as well everything works when pressing the alternative key 'L'.
On click it is not working because the flag `toggleSpotlightOnMouseDown` iis set to `false`. Can you please set it to `true` and retry it?

```
toggleSpotlightOnMouseDown: true // toggle spotlight by holding down the mouse key
```

**Comment by bcouetil** [comment]
Hello, thank you for your time.

You are right, I disabled it since it was not working. I'll active it soon for your to see the bug.

While we are at it, I can't figure out how to draw a cursor in presentation mode and not in spotlight mode.

You have these parameters : 

```
presentingCursor: 'none', // choose the cursor when spotlight is on. Maybe "crosshair"?
presentingCursorOnlyVisibleWhenSpotlightVisible: true, // true: cursor is always "none" except when spotlight is on. 
```

You would cover more use-cases (and be more explicit) if you had these parameters instead : 
```
presentingCursor: 'crosshair',
spotlightCursor: 'none',
```

**Comment by denniskniep** [comment]
> You would cover more use-cases if you had these parameters instead  `presentingCursor` and  `spotlightCursor`

Yeah, you are right. I like that Idea. Are you interested to implement that and make a PullRequest?

> I'll active it soon for your to see the bug.

Fell free to ping me

**Comment by bcouetil** [comment]
@denniskniep,

Sorry, I'm not a JS developer, and there is not enough comments in the code for me to help for now. I did not understand the code when seeing it, but I may try harder if I find some time 😄 

I activated it, presentation mode is now on with 'X', you can test with the mouse, please.

**Comment by denniskniep** [comment]
Hi,

> You would cover more use-cases if you had these parameters instead presentingCursor and spotlightCursor

#4  tackled that feature request and is merged now. Thx to @pastleo 


> on Chrome, the spotlight does not appear at all

I still can not reproduce it on chrome

> on Firefox, the spotlight appears on click but does not move with the mouse

Yes, same behaviour on my machine

please use the new version and set the option `disablingUserSelect` to `true`

Let me know if it solves the issue for you.

**Comment by bcouetil** [comment]
Thanks, this works now 😺 

For the record, juste before testing, it was working again on chrome, same observations as yours.
