### ISSUE TITLE
Make Spotlight in speaker notes appear in main slide?

### ISSUE THREAD

**Issue by dcaixinha** [denniskniep/reveal.js-plugin-spotlight#7]
Hey @denniskniep! First of all, thanks for this amazing package :pray: 

Is there any plan (or is it feasible) to make the spotlight on speaker notes to show up on the main window? If I press 'c' to toggle it in the speaker notes window it creates the spotlight, but it doesn't propagate back to the main window. Thank you :bowing_man:

**Comment by bcouetil** [comment]
Hey ! I suppose you closed this because you did not get any response ?

**Comment by dcaixinha** [comment]
Yes, unfortunately that's right.

**Comment by denniskniep** [comment]
Hi,
sorry, but that project is currently not on my priority list.
If you provide a PR, I can merge it
