### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by AhmadHuran** [denniskniep/reveal.js-plugin-spotlight#9]
A license indication of any kind is missing.

**Comment by mcanouil** [comment]
Indeed, @denniskniep What's the license? I would like to package your plugin as a [Quarto](https://quarto.org/) extension.

**Comment by denniskniep** [comment]
Indeed a license was missing here.

I added the [Apache-2.0 license](https://github.com/denniskniep/reveal.js-plugin-spotlight/blob/master/LICENSE.txt)
